### pybroker版本

In [1]:
import pybroker

pybroker.__version__

'1.2.7'

### 数据源例子

In [3]:
from pybroker.ext.data import AKShare

akshare = AKShare()
# You can substitute 000001.SZ with 000001, and it will still work!
# and you can set start_date as "20210301" format
# You can also set adjust to 'qfq' or 'hfq' to adjust the data,
# and set timeframe to '1d', '1w' to get daily, weekly data
df = akshare.query(
    symbols=['000001.SZ'],
    start_date='3/1/2021',
    end_date='3/1/2023',
    adjust="qfq",
    timeframe="1d",
)
df

Loading bar data...
Loaded bar data: 0:00:00

          date     symbol   open   high    low  close   volume
0   2021-03-01  000001.SZ  19.88  20.02  19.52  19.79  1125387
1   2021-03-02  000001.SZ  19.96  20.49  19.60  19.99  1473425
2   2021-03-03  000001.SZ  19.92  21.42  19.80  21.35  1919635
3   2021-03-04  000001.SZ  21.11  21.83  20.99  21.26  1213579
4   2021-03-05  000001.SZ  21.04  21.32  20.20  20.68   880171
..         ...        ...    ...    ...    ...    ...      ...
482 2023-02-23  000001.SZ  12.75  13.07  12.73  12.80   824491
483 2023-02-24  000001.SZ  12.77  12.78  12.55  12.61   729989
484 2023-02-27  000001.SZ  12.50  12.63  12.43  12.44   621462
485 2023-02-28  000001.SZ  12.50  12.60  12.36  12.53   607936
486 2023-03-01  000001.SZ  12.55  12.94  12.49  12.92  1223452

[487 rows x 7 columns]